import { signIn, signOut, useSession } from "next-auth/react";
import { useState, useEffect } from 'react'
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Anthropic from '@anthropic-ai/sdk';
import { Completion, CompletionCreateParams } from "@anthropic-ai/sdk/resources";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [responseText, setResponseText] = useState('');

  useEffect(() => {
    // Create a new instance of Anthropic with your API key
    const anthropic = new Anthropic({
      apiKey: 'my api key', // Replace with your actual API key or use process.env.ANTHROPIC_API_KEY
    });

    // Define the API call parameters
    const params: CompletionCreateParams = {
      prompt: `${Anthropic.HUMAN_PROMPT} how does a court case get to the Supreme Court?${Anthropic.AI_PROMPT}`,
      max_tokens_to_sample: 300,
      model: 'claude-2',
    };

    // Make the API call
    anthropic.completions.create(params)
      .then((completion: Completion) => {
        setResponseText(completion.toString());
      })
      .catch((error) => {
        console.error('An error occurred:', error);
      });
  }, []);
  
  return (
    <>
      <Head>
        <title>app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#E2FDFF] to-[#5465FF]">
        <div> 
          <h1>API Response:</h1>
          <p>{responseText}</p>
        </div>
        <div>
          <textarea className="box-border h-200 w-200 p-4 
                  border-4 m4">
                
          </textarea>
        </div>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            DollarDiagnosis
          </h1>
          <h2 className="The ">
            How do you feel?
          </h2>
          
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
      
    </>
    
  );
}



function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
